# Generated by Django 3.1.4 on 2021-01-06 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_contengt',
            new_name='comment_content',
        ),
    ]
